# @package _global_
model:
  n_layers: 8
  d_model: 512
  n_heads: 8
  d_head: 64
  d_mlp: 2048
  n_ctx: 2100
  film: false
  segment_embed: {enabled: true}

board:
  H: 32
  W: 32

train:
  bf16: true
  compile: {enabled: true, scope: "block"}
  batch_per_gpu: 32
  grad_accum: 1
  lr: 2e-4
  weight_decay: 0.1
  warmup_steps: 200
  steps: null
  target_tokens: 2.0e8
  seed: 123
  multi_steps: 0
  curriculum: {enabled: false, p_max: 0.5, start: 0, end: 1000}
  grad_clip: 1.0
  ema: {enabled: true, decay: 0.999}
  augment: {d4_prob: 0.5, shift_prob: 0.5}

interp:
  rule_battery: ["S23/B3","S23/B36","B2/S"]
