# @package _global_
defaults:
  - /model: base
  - /train: fast
  - /interp: default
  - _self_

exp:
  name: life32_t3

board:
  H: 32
  W: 32

model:
  n_layers: 8
  d_model: 512
  n_heads: 8
  d_head: 64
  d_mlp: 2048
  n_ctx: 5000   # >= 4119 needed for t+3 on 32x32
  film: false

train:
  bf16: true
  compile: {enabled: true, scope: "block"}
  batch_per_gpu: 1        # very conservative for long-seq attention
  grad_accum: 1
  lr: 3e-4
  weight_decay: 0.1
  warmup_steps: 200
  steps: null
  target_tokens: 2.0e8
  seed: 123
  multi_steps: 3          # enable t+1, t+2, t+3 targets
  curriculum: {enabled: true, p_max: 0.5, start: 0, end: 2000}

interp:
  rule_battery: ["S23/B3","S23/B36","B2/S"]
